name: Azure AppService Deploy

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read
    
env:
  NODEJS_VERSION: 18.X

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v2.1.5
        with:
          node-version: ${{ env.NODEJS_VERSION }}
          cache: "npm"
          cache-dependency-path: "./package-lock.json"
      - name: Install dependencies
        run: npm ci
      - name: Build Node.js App
        run: npm run build
      - name: Test Node.js App
        run: npm run test
      - name: Azure login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ secrets.AZURE_WEBAPP_NAME }}
          package: .
      - name: Azure logout
        run: |
          az logout
